openapi: 3.0.0
info:
  description: Products PDF Generator
  version: 1.1.3
  title: Quickstart service Demo
tags:
  - name: pdf
    description: Products PDF
paths:
  /download-pdf:
    get:
      summary: Method to retrieve one pdf
      description: This method download a pdf
      operationId: downloadPDF
      responses:
        "200":
          description: successful operation
          content:
            application/pdf:
              schema:
                type: string
                format: byte
        "400":
          description: Bad Request
          content:
            application/pdf:
              schema:
                $ref: "#/components/schemas/ErrorResourceResponse"
        "401":
          description: Unauthorized
          content:
            application/pdf:
              schema:
                $ref: "#/components/schemas/ErrorResourceResponse"
        "403":
          description: Forbidden
          content:
            application/pdf:
              schema:
                $ref: "#/components/schemas/ErrorResourceResponse"
        "404":
          description: Not Found
          content:
            application/pdf:
              schema:
                $ref: "#/components/schemas/ErrorResourceResponse"
        "500":
          description: Internal Server Error
          content:
            application/pdf:
              schema:
                $ref: "#/components/schemas/ErrorResourceResponse"
components:
  schemas:
    ErrorResource:
      type: object
      properties:
        code:
          type: string
        description:
          type: string
        details:
          type: array
          items:
            type: string
      title: ErrorResource
    ErrorResourceResponse:
      type: object
      properties:
        error:
          $ref: "#/components/schemas/ErrorResource"
